### ISSUE TITLE
Управление кэшированием ресурсов в CSS

### ISSUE THREAD

**Issue by monochromer** [monochromer/frontend-interview#37]
Пусть есть очень большой CSS-файл, в котором есть ссылка на картинку:
```css
body {
  background-image: url('/url-to-image.jpg')
}
/* 500kb */
```

Можно ли как-то сделать так, чтобы при изменении картинки, пользователь получил обновлённую картинку, но не загрузил заново CSS-файл.
